In [75]:
import nltk
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
import json
from joblib import dump

In [76]:
with open("../data/aff_neg_data.json") as f:
    content = json.load(f)

examples = []

for item in content:
    for value in item["examples"]:
        examples.append([value, item["class"]])

In [77]:
df = pd.DataFrame(examples, columns=["example", "label"])
df

example     label
0              Yes, thank you!  positive
1                   Yes, I do!  positive
2                  Yes please.  positive
3               Yes of course.  positive
4                         Yes.  positive
5               No, thank you!  negative
6  I don't want anything else.  negative
7            No, nothing else.  negative
8                          No.  negative

In [78]:
le = LabelEncoder()
le.fit(df["label"])

LabelEncoder()

In [79]:
df["label"] = le.transform(df["label"])
df

example  label
0              Yes, thank you!      1
1                   Yes, I do!      1
2                  Yes please.      1
3               Yes of course.      1
4                         Yes.      1
5               No, thank you!      0
6  I don't want anything else.      0
7            No, nothing else.      0
8                          No.      0

In [80]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["example"])

In [81]:
X.shape

(9, 13)

In [82]:
classifier = GaussianNB()
classifier.fit(X.toarray(), df["label"])

GaussianNB()

In [83]:
preds = []
for i, row in df.iterrows():
    vector = vectorizer.transform([row["example"]])
    result = classifier.predict(vector.toarray())
    preds.append(result)

preds

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0])]

In [84]:
acc_score = accuracy_score(df["label"], preds)
acc_score

1.0

In [85]:
model_path = "../models/aff_neg_clf.joblib"
dump(classifier, model_path)

['../models/aff_neg_clf.joblib']

In [87]:
vector = vectorizer.transform(["No, but I would like something else."])
result = classifier.predict(vector.toarray())
result

array([0])